# Travis CI Integration

sudo: required

language: c++
compiler:
  - gcc
  - clang

script: ./autogen.sh && ./configure && make -j2

before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ xenial main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y autoconf-archive check
