# Travis CI configuration

sudo: required
dist: trusty

before_install:
# Add Xenial repository and pull enough so that installing build-deps will not fail. (newer dpkg needed)
  - sudo add-apt-repository -y "deb http://de.archive.ubuntu.com/ubuntu/ xenial main"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 0xEFE21092
  - sudo apt-get -q update
  - sudo apt-get install -y -q dpkg
# Add Debian-sid repository -- Newer Ubuntu's are not available, so we need to mix Ubuntu and Debian :-/
# (we need a more recent autoconf-archive)
  - sudo add-apt-repository -y "deb http://ftp.us.debian.org/debian unstable main"
  - curl 'https://ftp-master.debian.org/keys/archive-key-7.0.asc' | sudo apt-key add -
  - curl 'https://ftp-master.debian.org/keys/archive-key-8.asc' | sudo apt-key add -
  - sudo apt-get -q update
  - sudo apt-get -y -q install check autoconf automake autoconf-archive libtool build-essential

# be nice: only pull a shallow copy
git:
  depth: 3

# build configuration:
# - cpp -- because of the c++ example
# - try both: clang and gcc.
# - as we do not store configure in the repository, bootstrap accordingly.

language: cpp

compiler:
  - gcc
  - clang

script:
 - ./autogen.sh
 - ./configure || cat config.log
 - make || ( cat Makefile && exit 1)
 - make check || ( cat test-suite.log && exit 1)
