# Travis CI configuration

sudo: required
dist: trusty

before_install:
# Add Xenial repository and pull enough so that installing build-deps will not fail. (newer dpkg needed)
  - sudo add-apt-repository -y "deb http://de.archive.ubuntu.com/ubuntu/ xenial main"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 0xEFE21092
  - sudo apt-get -q update
  - sudo apt-get install -y -q dpkg
# Add Debian-sid repository -- Newer Ubuntu's are not available, so we need to mix Ubuntu and Debian :-/
# (we need a more recent autoconf-archive)
  - sudo add-apt-repository -y "deb http://ftp.us.debian.org/debian unstable main"
  - curl 'https://ftp-master.debian.org/keys/archive-key-7.0.asc' | sudo apt-key add -
  - curl 'https://ftp-master.debian.org/keys/archive-key-8.asc' | sudo apt-key add -
  - sudo apt-get -q update
  - sudo apt-get -y -q install check autoconf automake autoconf-archive libtool build-essential

# be nice: only pull a shallow copy
git:
  depth: 3

# build configuration:
# - cpp -- because of the c++ example
# - try both: clang and gcc.
# - as we do not store configure in the repository, bootstrap accordingly.

language: cpp

compiler:
  - gcc

script:
 - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./autogen.sh; fi
 - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./configure || cat config.log; fi
 - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make || ( cat Makefile && exit 1); fi
 - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make check || ( cat test-suite.log && exit 1); fi

# See if coverity can be integrated...
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "xd+V0aOPr5dFS5xHZD1Ab6nQG531NcKRU3piEyC1PwVuzRSvLjY8+myLND8RO+TKDzWFxWHyXIsSm9lMLDiaMR6GgaI331rRIJe3mW2tO8oTdBxME60QTLbR1bIgMnW5DHiOp//jh+OOf2qT+ZOFXT3rOdEnSgBhJ2zugHLkjjZgJVWPNRFDKeMt9OCXHNjm/qQMgJOX8xshzhqGebCK7Q3hPpi+fCzpdqEdpjn6eObc/xl4cLDtFkSE+sYhOdhmMD3AbDP26TTa47suwk09zMmEskAuME4TNseP8Z/2QJ322sX6uyDCNp8lg02ujqI6/VBywKj2zhsdWqg/v+LzNYtcNXqTOYBOUKnRqhFlQ3IAtjFlKh9BCMLjHlchIkSKeNKheLwMjl/eB7JpNShyIhmTdCMfHTl40G6/2bBFCd+KNgPfO7b3YjOJuaQxHSzGKc7/ItIfCbFS39fWVXSby76zN0xPvtSjZ6MEoZ9jkhgpacmIjYyvw2GyxJjmSqL1LReJN2/EC/E6gF84HXc3RJCRxUPWUt5QzpOdvQwBN8jP9iBm/7L0YRdH+1wqz80n1F1ctb4EZ6TmxcOIiwdQQLoNWQ2KV0j/Oad5BDf0NwuSkMS/zdPxp/jiLoQdod72IOU2TILOIRy5yDoK3+K15bM4DJH0K1QwebPZzkTSXTI="

addons:
  coverity_scan:
    project:
      name: "coldtobi/liblightify"
      description: "Build submitted via Travis CI"
    notification_email: tobi@coldtobi.de
    build_command_prepend: "./autogen.sh ; ./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
